name: Gdip CICD deployment workshop2
on:
  push:
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setup-node@v3
        with: 
          node-version: '18'

      - name: deploy
        uses: bervProject/railway-deploy@main
        with:
          railway_token: ${{ secrets.RAILWAY_TOKEN }}
          service: "dov-bear_2023_04_28-07_34_04"