name: Gdip CICD deployment workshop2
on:
  push:
    branches:
    - 'features/*'
    tags:
    - '^v[0-9]+\.[0-9]+\.[0-9]+$'
jobs: 
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup nodejs
        uses: actions/setupnode@v3
        with: 
          node-version: '17'