name: Gdip CICD deployment workshop2
on:
  push:
    branches:
      - 'release/*'
      - '!master'
    tags: ['^v[0-9]+.[0-9]+$']
jobs: 
  deploy:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '#NORUN')"
    steps:
      # - name: Checkout
      #   uses: actions/checkout@v3
          
      # - name: Install Railway
      #   run: npm i -g @railway/cli

      # - name: deploy
      #   run: railway up
      #   env:
      #     RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      
      - name: Send custom JSON data to Slack workflow
        uses: slackapi/slack-github-action@v1.18.0
        id: cicidtest
        with:
          channe-id: '#cicdtest'
          # payload: |
          #   {
          #     "text": "*DipSA 56 CI/CD Submission* \n\n *Name* :Cheng Jun Long \t *Email* :E1112916@u.nus.edu\n *Matriculation:* E111291\t *Repository:*\n ${{ secrets.RAILWAY_URL }} \n ${{ secrets.RAILWAY_URL }} "
          #   }
          payload: |
            {
              "attachments": [
                  {
                      "fallback": "요청 실패 시 보낼 메시지",
                      "color": "#2eb886",
                      "pretext": "attachment block 위에 나타낼 text",
                      "author_name": "roseline",
                      "author_link": "https://github.com/roseline124",
                      "author_icon": "https://avatars.githubusercontent.com/u/41788121?s=460&u=ee6a6f6499aa68a23947cfb76d5e9cb6eebfd29c&v=4",
                      "title": "attachments 사용법",
                      "title_link": "https://api.slack.com/",
                      "text": "attachment block 안에 보여줄 메시지",
                      "fields": [
                          {
                              "title": "필드",
                              "value": "value",
                              "short": false
                          }
                      ],
                      "image_url": "http://my-website.com/path/to/image.jpg",
                      "thumb_url": "http://example.com/path/to/thumb.png",
                      "footer": "Slack API",
                      "footer_icon": "https://platform.slack-edge.com/img/default_application_icon.png",
                      "ts": 123456789
                  }
              ]
            }   
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_TESTTEST }}
